nginx:
  domains:
    - host: testnet.toncenter.com
      analytics_enabled: true
      index_page_enabled: true
  index_folder: index_page/testnet
pyton:
  request_timeout: 20
  webserver_workers: 1
  parallel_requests_per_liteserver: 50
  get_methods: true
  json_rpc: true
  liteserver_config: config/testnet.json
  keystore: ./ton_keystore/
  cdll: null
logs:
  enabled: false
  log_successful_requests: false
  mongodb:
    host: mongodb
    port: 27017
    database: pyton
    username: user1
    password_file: /run/secrets/mongodb_password
cache:
  enabled: false
  redis:
    endpoint: cache_redis
    port: 6379
    timeout: 1
ratelimit:
  enabled: true
  redis:
    endpoint: ratelimit_redis
    port: 6379
    timeout: 1
  token_bot:
    token_file: /run/secrets/token_file
  token_redis:
    endpoint: token_redis
    port: 6379