#!/usr/bin/env python3

import sys
import jinja2
import yaml


def gen_nginx_conf(settings_file, input_file, output_file):
    print("👷 Generating config for nginx...")

    with open(settings_file, 'r') as f:
        settings = yaml.safe_load(f)

    with open(input_file, 'r') as f:
        template = jinja2.Template(f.read())
    template_args = {
        'analytics_enabled' : settings['logs']['enabled'],
        'domains' : settings['nginx']['domains']
    }
    outputText = template.render(template_args)
    outputText = "# This file was automatically generated by gen_config.py\n" + outputText
    
    with open(output_file, 'w') as f:
        f.write(outputText)

    print("✅ Config for nginx created.")

def main():
    gen_nginx_conf(sys.argv[1], sys.argv[2], sys.argv[3])

if __name__ == '__main__':
    main()