# Logs settings.
logs:
  enabled: $TON_API_LOGS_ENABLED
  api_root_path: $TON_API_ANALYTICS_ROOT_PATH
  log_successful_requests: $TON_API_LOGS_LOG_SUCCESSFUL
  record_ttl: 86400
  mongodb:
    host: $TON_API_LOGS_MONGODB_HOST
    port: $TON_API_LOGS_MONGODB_PORT
    database: $TON_API_LOGS_MONGODB_DATABASE
    username: $TON_API_LOGS_MONGODB_USERNAME
    password_file: $TON_API_LOGS_MONGODB_PASSWORD_FILE
